//! Frozen word-ladder dictionary — parity with the TypeScript word list.

pub const WORDS: &[&str] = &[
    "able", "about", "above", "abuse", "ace", "ache", "acid", "act", "actor", "adapt", "add",
    "admit", "adopt", "adult", "after", "again", "age", "aged", "ago", "agree", "ahead", "aid",
    "aide", "aim", "air", "ajar", "alarm", "album", "alert", "alien", "align", "alike", "alive",
    "all", "allow", "alone", "along", "also", "alter", "among", "and", "angel", "anger", "angle",
    "angry", "ant", "any", "apart", "ape", "apple", "apply", "arc", "arch", "are", "area", "arena",
    "argue", "arise", "ark", "arm", "armor", "army", "array", "arrow", "art", "ash", "aside",
    "ask", "asset", "ate", "aunt", "auto", "avoid", "awake", "award", "aware", "away", "axle",
    "baby", "back", "bad", "bade", "bag", "bail", "bait", "bake", "bald", "bale", "ball", "ban",
    "band", "bane", "bank", "bar", "bare", "bark", "barn", "base", "basic", "basis", "bat", "bath",
    "bay", "beach", "bead", "beak", "beam", "bean", "bear", "beat", "bed", "bee", "beef", "been",
    "beer", "begun", "being", "bell", "below", "belt", "bench", "bend", "bent", "best", "bet",
    "bid", "big", "bile", "bill", "bin", "bind", "bird", "birth", "bit", "bite", "black", "blame",
    "blank", "blast", "blaze", "blend", "bless", "blind", "block", "blood", "blow", "blown",
    "blue", "blur", "boar", "board", "boas", "boat", "bock", "body", "bog", "bold", "bolt", "bomb",
    "bond", "bone", "book", "boom", "boon", "boos", "boost", "boot", "booth", "bore", "born",
    "boss", "both", "bound", "bout", "bow", "bowl", "box", "boy", "brag", "brain", "brake", "bran",
    "brand", "brave", "bread", "break", "bred", "breed", "brew", "brick", "bride", "brief", "brim",
    "bring", "bro", "broad", "broke", "brown", "brush", "buck", "bud", "bug", "build", "bulk",
    "bull", "bump", "bun", "bunch", "burn", "burst", "bury", "bus", "bush", "bust", "busy", "but",
    "buy", "buyer", "buzz", "cab", "cabin", "cable", "cage", "cake", "calf", "call", "calm",
    "came", "camp", "can", "candy", "cane", "cap", "cape", "car", "card", "care", "cargo", "carry",
    "cart", "case", "cash", "cast", "cat", "catch", "cause", "cave", "cell", "cent", "chain",
    "chair", "chase", "chat", "cheap", "check", "chef", "chest", "chief", "child", "china", "chip",
    "chop", "cite", "city", "clad", "claim", "clam", "clap", "class", "claw", "clay", "clean",
    "clear", "climb", "clip", "clock", "close", "cloud", "club", "clue", "coach", "coal", "coast",
    "coat", "code", "cog", "coil", "coin", "cold", "colt", "come", "cone", "cook", "cool", "coop",
    "cop", "cope", "copy", "cord", "core", "cork", "corn", "cost", "cot", "count", "coup", "court",
    "cove", "cover", "cow", "crab", "crack", "craft", "crash", "crazy", "cream", "crew", "crib",
    "crime", "crop", "cross", "crow", "crowd", "crown", "cruel", "crush", "cry", "cub", "cube",
    "cult", "cup", "curb", "cure", "curl", "curve", "cut", "cute", "dad", "dale", "dam", "dame",
    "damp", "dare", "dark", "darn", "dart", "dash", "data", "date", "dawn", "day", "days", "dead",
    "deaf", "deal", "dean", "dear", "debt", "deck", "deed", "deem", "deep", "deer", "demo", "den",
    "deny", "desk", "dew", "dial", "dice", "did", "die", "died", "diet", "dig", "dim", "dime",
    "ding", "dip", "dirt", "disc", "dish", "disk", "diss", "dive", "dock", "does", "dog", "doll",
    "dome", "done", "doom", "door", "dose", "dot", "dove", "down", "drab", "drag", "draw", "drew",
    "drip", "drop", "drug", "drum", "dry", "dual", "dub", "duck", "dud", "dude", "due", "duel",
    "dues", "dug", "duke", "dull", "duly", "dumb", "dump", "dune", "dung", "dunk", "dusk", "dust",
    "duty", "dye", "each", "ear", "earl", "earn", "ease", "east", "easy", "eat", "eats", "echo",
    "edge", "edit", "egg", "ego", "elf", "elk", "elm", "else", "emit", "emu", "end", "ends", "era",
    "eve", "even", "ever", "evil", "ewe", "exam", "exit", "eye", "eyes", "face", "fact", "fad",
    "fade", "fail", "fair", "fake", "fall", "fame", "fan", "far", "fare", "farm", "fart", "fast",
    "fat", "fate", "fax", "fear", "feat", "fed", "fee", "feed", "feel", "feet", "fell", "felt",
    "fern", "fest", "feud", "few", "fig", "file", "fill", "film", "fin", "find", "fine", "fink",
    "fir", "fire", "firm", "fish", "fist", "fit", "five", "fix", "flag", "flap", "flat", "flaw",
    "flea", "fled", "flee", "flew", "flip", "flit", "flog", "flow", "flux", "fly", "foam", "foe",
    "foes", "fog", "foil", "fold", "folk", "fond", "font", "food", "fool", "foot", "for", "fore",
    "fork", "form", "fort", "foul", "four", "fowl", "fox", "free", "fret", "frog", "from", "fry",
    "fuel", "full", "fun", "fund", "fur", "fuse", "fuss", "gab", "gag", "gage", "gain", "gait",
    "gale", "game", "gang", "gap", "gas", "gasp", "gate", "gave", "gaze", "gear", "gel", "gem",
    "gene", "get", "gift", "gig", "gilt", "gin", "girl", "give", "glad", "glen", "glow", "glue",
    "glut", "gnaw", "gnu", "goad", "goal", "goat", "god", "goes", "gold", "golf", "gone", "good",
    "gore", "gory", "got", "gown", "grab", "gram", "gray", "grew", "grey", "grid", "grim", "grin",
    "grip", "grit", "grow", "grub", "gulf", "gum", "gun", "gust", "gut", "guts", "guy", "gym",
    "hack", "had", "hag", "hail", "hair", "hale", "half", "hall", "halt", "ham", "hand", "hang",
    "hard", "hare", "harm", "harp", "hart", "has", "hash", "hat", "hate", "haul", "have", "hawk",
    "hay", "haze", "hazy", "head", "heal", "heap", "hear", "heat", "heed", "heel", "heir", "held",
    "hell", "helm", "help", "hem", "hemp", "hen", "her", "herb", "herd", "here", "hero", "hew",
    "hex", "hid", "hide", "hie", "high", "hike", "hill", "hilt", "him", "hind", "hint", "hip",
    "hire", "his", "hit", "hive", "hoax", "hob", "hoe", "hog", "hoke", "hold", "hole", "holy",
    "home", "hone", "hood", "hoof", "hook", "hop", "hope", "horn", "hose", "host", "hot", "hour",
    "hove", "how", "howl", "hub", "hubs", "hue", "hug", "huge", "hull", "hum", "hump", "hung",
    "hunt", "hurt", "hush", "hut", "ice", "icon", "icy", "idea", "idle", "idol", "ill", "imp",
    "inch", "info", "ink", "inn", "into", "ion", "ire", "irk", "iron", "isle", "item", "its",
    "ivy", "jab", "jack", "jade", "jag", "jail", "jam", "jar", "jaw", "jay", "jazz", "jeep",
    "jerk", "jest", "jet", "jig", "job", "jog", "join", "joke", "jolt", "jot", "joy", "judo",
    "jug", "jump", "junk", "jury", "just", "jut", "keen", "keep", "keg", "ken", "kept", "key",
    "kick", "kid", "kill", "kin", "kind", "king", "kit", "kite", "knee", "knew", "knit", "knob",
    "knot", "know", "lab", "labs", "lace", "lack", "lacy", "lad", "lag", "laid", "lair", "lake",
    "lamb", "lame", "lamp", "land", "lane", "lap", "lard", "lark", "lash", "last", "late", "laud",
    "law", "lawn", "laws", "lay", "lazy", "lead", "leaf", "leak", "lean", "leap", "led", "left",
    "leg", "lend", "lens", "lent", "less", "lest", "let", "liar", "lice", "lick", "lid", "lids",
    "lie", "lien", "lies", "lieu", "life", "lift", "like", "lily", "limb", "lime", "limo", "limp",
    "line", "link", "lion", "lip", "lips", "list", "lit", "lite", "live", "load", "loaf", "loan",
    "lobe", "lock", "loft", "log", "lone", "long", "look", "loom", "loop", "loot", "lop", "lord",
    "lore", "lose", "loss", "lost", "lot", "lots", "loud", "love", "low", "luck", "lug", "lump",
    "lung", "lure", "lurk", "lush", "lust", "lute", "mace", "mad", "made", "maid", "mail", "main",
    "make", "male", "mall", "malt", "man", "mane", "many", "map", "maps", "mar", "mare", "mark",
    "mars", "mash", "mask", "mass", "mast", "mat", "mate", "math", "mats", "maw", "may", "maze",
    "mead", "meal", "mean", "meat", "meek", "meet", "meld", "melt", "memo", "men", "mend", "menu",
    "mere", "mesh", "mess", "met", "mice", "mid", "mild", "mile", "milk", "mill", "mind", "mine",
    "mint", "miss", "mist", "mite", "mitt", "mix", "moan", "moat", "mob", "mock", "mode", "mold",
    "mole", "molt", "mom", "monk", "mood", "moon", "moor", "mop", "more", "morn", "moss", "most",
    "moth", "move", "much", "muck", "mud", "mug", "mule", "mull", "mum", "muse", "mush", "musk",
    "must", "mute", "nab", "nag", "nags", "nail", "name", "nap", "nape", "nard", "navy", "nay",
    "near", "neat", "neck", "nee", "need", "nest", "net", "nets", "new", "news", "next", "nice",
    "nick", "nil", "nine", "nip", "nit", "nob", "nod", "node", "none", "noon", "nope", "nor",
    "norm", "nose", "not", "note", "noun", "now", "nub", "nude", "numb", "nun", "nut", "nuts",
    "oak", "oaks", "oar", "oat", "oath", "obey", "odd", "odds", "ode", "odor", "off", "oft", "oil",
    "oils", "okay", "old", "omen", "omit", "once", "one", "only", "onto", "open", "opt", "opts",
    "oral", "orb", "ore", "our", "ours", "oust", "out", "outs", "oven", "over", "owe", "owed",
    "owes", "owl", "own", "owns", "pace", "pack", "pact", "pad", "page", "paid", "pail", "pain",
    "pair", "pal", "pale", "palm", "pan", "pane", "pang", "pans", "pant", "pap", "par", "pare",
    "park", "part", "pass", "past", "pat", "path", "pave", "paw", "pawn", "pay", "pays", "pea",
    "peak", "pear", "peas", "peat", "peck", "peek", "peel", "peer", "peg", "pelt", "pen", "pens",
    "pep", "per", "perk", "perm", "pert", "pest", "pet", "pets", "pew", "pick", "pie", "pier",
    "pies", "pig", "pigs", "pike", "pile", "pill", "pin", "pine", "ping", "pink", "pins", "pint",
    "pipe", "piss", "pit", "pits", "pity", "plan", "play", "plea", "plod", "plop", "plot", "plow",
    "ploy", "plug", "plum", "plus", "ply", "pod", "pods", "poem", "poet", "poke", "pole", "poll",
    "polo", "pomp", "pond", "pony", "pool", "poop", "poor", "pop", "pope", "pops", "pore", "pork",
    "porn", "port", "pose", "posh", "post", "pot", "pour", "pout", "pow", "pray", "prep", "prey",
    "pro", "prod", "prop", "prow", "pry", "pub", "puff", "pug", "pull", "pulp", "pump", "pun",
    "punk", "puns", "pup", "pure", "pus", "push", "put", "puts", "putt", "quad", "quay", "quit",
    "quiz", "race", "rack", "raft", "rag", "rage", "rags", "raid", "rail", "rain", "rake", "ram",
    "ramp", "ran", "rang", "rank", "rant", "rap", "raps", "rapt", "rare", "rash", "rasp", "rat",
    "rate", "rats", "rave", "raw", "ray", "rays", "raze", "read", "real", "ream", "reap", "rear",
    "red", "redo", "ree", "reed", "reef", "reek", "reel", "ref", "refs", "rein", "rely", "rend",
    "rent", "rep", "repo", "rest", "rib", "ribs", "rice", "rich", "rid", "ride", "rife", "rift",
    "rig", "rigs", "rile", "rill", "rim", "rims", "rind", "ring", "riot", "rip", "ripe", "rise",
    "risk", "rite", "road", "roam", "roar", "rob", "robe", "robs", "rock", "rod", "rode", "rods",
    "roe", "role", "roll", "romp", "roof", "room", "root", "rope", "rose", "rosy", "rot", "rote",
    "rots", "rout", "rove", "row", "rows", "rub", "rubs", "ruby", "ruck", "rude", "rue", "rued",
    "rues", "ruff", "rug", "rugs", "ruin", "rule", "rum", "rump", "rums", "run", "rune", "rung",
    "runs", "runt", "ruse", "rush", "rust", "rut", "ruts", "rye", "sac", "sack", "sad", "safe",
    "sag", "saga", "sage", "said", "sail", "sake", "sale", "salt", "same", "sand", "sane", "sang",
    "sank", "sap", "saps", "sash", "sat", "sate", "save", "saw", "sawn", "say", "says", "scab",
    "scam", "scan", "scar", "sea", "seal", "seam", "sear", "seas", "seat", "sec", "sect", "seed",
    "seek", "seem", "seen", "seep", "self", "sell", "semi", "send", "sent", "sept", "set", "sets",
    "sew", "sewn", "shag", "sham", "shaw", "shay", "she", "shed", "shim", "shin", "ship", "shiv",
    "shmo", "shoe", "shoo", "shop", "shot", "show", "shun", "shut", "shy", "sic", "sick", "side",
    "sigh", "sign", "silk", "sill", "silt", "sin", "sine", "sing", "sink", "sip", "sir", "sire",
    "sis", "sit", "site", "sits", "six", "size", "skew", "ski", "skid", "skim", "skin", "skip",
    "sky", "slab", "slag", "slam", "slap", "slat", "slay", "sled", "slew", "slid", "slim", "slit",
    "slob", "slop", "slot", "slow", "slug", "slum", "slur", "sly", "smog", "snag", "snap", "snip",
    "snob", "snot", "snow", "snub", "snug", "soak", "soap", "soar", "sob", "sobs", "sock", "sod",
    "soda", "sods", "sofa", "soft", "soil", "soke", "sold", "sole", "solo", "some", "son", "song",
    "sons", "soon", "soot", "sop", "sops", "sore", "sort", "sot", "sots", "soul", "soup", "sour",
    "sow", "soy", "spa", "span", "spar", "spas", "spat", "spec", "sped", "spin", "spit", "spot",
    "spry", "spud", "spur", "spy", "stab", "stag", "star", "stat", "stay", "stem", "step", "stew",
    "stir", "stop", "stow", "stub", "stud", "stun", "sty", "sub", "such", "suck", "suds", "sue",
    "sued", "sues", "suit", "sulk", "sum", "sums", "sun", "sung", "sunk", "suns", "sup", "sure",
    "surf", "swab", "swam", "swan", "swap", "swat", "sway", "swim", "swum", "tab", "tabs", "tack",
    "tact", "tad", "tag", "tags", "tail", "take", "tale", "talk", "tall", "tame", "tan", "tang",
    "tank", "tap", "tape", "taps", "tar", "tart", "task", "tat", "taut", "tax", "taxi", "tea",
    "teak", "teal", "team", "tear", "teas", "tech", "teem", "teen", "tell", "temp", "ten", "tend",
    "tens", "tent", "term", "test", "text", "than", "that", "thaw", "the", "them", "then", "they",
    "thin", "this", "thou", "thud", "thug", "thus", "thy", "tic", "tick", "tide", "tidy", "tie",
    "tied", "tier", "ties", "tile", "till", "tilt", "time", "tin", "tine", "tins", "tiny", "tip",
    "tips", "tire", "tit", "toad", "toe", "toes", "tofu", "tog", "togs", "toil", "told", "toll",
    "tom", "tomb", "tome", "ton", "tone", "tong", "tons", "too", "took", "tool", "toot", "top",
    "tops", "tore", "torn", "tort", "toss", "tot", "tote", "tots", "tour", "tow", "town", "toy",
    "toys", "tram", "trap", "tray", "tree", "trek", "trim", "trio", "trip", "trod", "trot", "true",
    "try", "tsar", "tub", "tube", "tubs", "tuck", "tuff", "tuft", "tug", "tugs", "tun", "tuna",
    "tune", "tunk", "turf", "turn", "tutu", "twig", "twin", "twit", "twos", "type", "ugh", "ugly",
    "ump", "undo", "unit", "unto", "upon", "urge", "urn", "use", "used", "user", "uses", "vain",
    "vale", "vamp", "van", "vane", "vary", "vase", "vast", "vat", "vats", "veal", "veer", "veil",
    "vein", "vent", "verb", "very", "vest", "vet", "veto", "vets", "via", "vial", "vice", "vide",
    "vie", "vied", "vies", "view", "vile", "vim", "vine", "visa", "vise", "void", "volt", "vote",
    "vow", "vows", "wad", "wade", "wads", "wag", "wage", "wail", "wain", "wait", "wake", "walk",
    "wall", "wand", "want", "war", "ward", "ware", "warm", "warn", "warp", "wars", "wart", "wary",
    "was", "wash", "wasp", "wast", "wave", "wavy", "wax", "waxy", "way", "ways", "weak", "weal",
    "wear", "web", "wed", "weds", "wee", "weed", "week", "weep", "weld", "well", "went", "wept",
    "were", "west", "wet", "wets", "what", "when", "whet", "whew", "whim", "whip", "whir", "whiz",
    "who", "whom", "why", "wick", "wide", "wife", "wig", "wigs", "wild", "wile", "will", "wilt",
    "wily", "wimp", "win", "wind", "wine", "wing", "wink", "wino", "wins", "wipe", "wire", "wiry",
    "wise", "wish", "wisp", "wit", "wits", "woe", "woes", "wok", "woke", "wolf", "womb", "won",
    "wont", "woo", "wood", "wool", "woos", "word", "wore", "work", "worm", "worn", "wort", "wove",
    "wow", "wrap", "wren", "writ", "yak", "yam", "yap", "yard", "yarn", "yaw", "yawn", "yea",
    "year", "yell", "yelp", "yes", "yet", "yew", "yin", "yoke", "yolk", "yore", "you", "your",
    "yow", "yowl", "yule", "yup", "yurt", "zany", "zap", "zaps", "zeal", "zed", "zee", "zen",
    "zero", "zest", "zinc", "zip", "zips", "zit", "zits", "zone", "zoo", "zoom", "zoos",
];
