//! Frozen Hunt theme lists — order matches the TypeScript generator.

pub struct Theme {
    pub name: &'static str,
    pub words: &'static [&'static str],
}

pub const THEMES: &[Theme] = &[
    Theme {
        name: "Animals",
        words: &[
            "LION", "TIGER", "BEAR", "WOLF", "EAGLE", "SHARK", "WHALE", "SNAKE", "HORSE", "ZEBRA",
            "PANDA", "KOALA", "RABBIT", "MONKEY", "DOLPHIN", "PENGUIN", "GIRAFFE", "ELEPHANT",
            "LEOPARD", "CHEETAH",
        ],
    },
    Theme {
        name: "Fruits",
        words: &[
            "APPLE", "BANANA", "ORANGE", "GRAPE", "MANGO", "PEACH", "PEAR", "PLUM", "LEMON",
            "LIME", "MELON", "CHERRY", "BERRY", "PAPAYA", "GUAVA", "KIWI", "FIG", "DATE",
            "COCONUT", "APRICOT",
        ],
    },
    Theme {
        name: "Colors",
        words: &[
            "RED", "BLUE", "GREEN", "YELLOW", "ORANGE", "PURPLE", "PINK", "BLACK", "WHITE",
            "BROWN", "GRAY", "GOLD", "SILVER", "VIOLET", "INDIGO", "CYAN", "MAROON", "NAVY",
            "TEAL", "OLIVE",
        ],
    },
    Theme {
        name: "Sports",
        words: &[
            "SOCCER",
            "TENNIS",
            "GOLF",
            "HOCKEY",
            "RUGBY",
            "BOXING",
            "SKIING",
            "DIVING",
            "ROWING",
            "FENCING",
            "ARCHERY",
            "CYCLING",
            "RUNNING",
            "SWIMMING",
            "SURFING",
            "BOWLING",
            "BASEBALL",
            "BASKETBALL",
            "FOOTBALL",
            "VOLLEYBALL",
        ],
    },
    Theme {
        name: "Countries",
        words: &[
            "FRANCE", "SPAIN", "ITALY", "GERMANY", "BRAZIL", "JAPAN", "CHINA", "INDIA", "EGYPT",
            "GREECE", "MEXICO", "CANADA", "SWEDEN", "NORWAY", "POLAND", "TURKEY", "RUSSIA", "PERU",
            "CHILE", "KENYA",
        ],
    },
    Theme {
        name: "Weather",
        words: &[
            "SUNNY",
            "RAINY",
            "CLOUDY",
            "WINDY",
            "FOGGY",
            "STORM",
            "SNOW",
            "HAIL",
            "FROST",
            "SLEET",
            "THUNDER",
            "LIGHTNING",
            "RAINBOW",
            "BREEZE",
            "DRIZZLE",
            "BLIZZARD",
            "TORNADO",
            "HURRICANE",
            "MONSOON",
            "HEAT",
        ],
    },
    Theme {
        name: "Music",
        words: &[
            "PIANO",
            "GUITAR",
            "DRUMS",
            "VIOLIN",
            "FLUTE",
            "TRUMPET",
            "HARP",
            "CELLO",
            "BASS",
            "SAXOPHONE",
            "CLARINET",
            "HARMONICA",
            "BANJO",
            "MELODY",
            "RHYTHM",
            "CHORUS",
            "VERSE",
            "BEAT",
            "TEMPO",
            "HARMONY",
        ],
    },
    Theme {
        name: "Space",
        words: &[
            "STAR", "MOON", "PLANET", "COMET", "METEOR", "GALAXY", "NEBULA", "ORBIT", "ROCKET",
            "SATURN", "JUPITER", "MARS", "VENUS", "NEPTUNE", "URANUS", "PLUTO", "ASTEROID",
            "COSMOS", "SOLAR", "LUNAR",
        ],
    },
    Theme {
        name: "Food",
        words: &[
            "BREAD", "CHEESE", "PIZZA", "PASTA", "RICE", "SOUP", "SALAD", "STEAK", "CHICKEN",
            "FISH", "BURGER", "TACO", "SUSHI", "CURRY", "NOODLE", "WAFFLE", "PANCAKE", "SANDWICH",
            "PRETZEL", "COOKIE",
        ],
    },
    Theme {
        name: "Nature",
        words: &[
            "TREE",
            "FLOWER",
            "RIVER",
            "OCEAN",
            "MOUNTAIN",
            "VALLEY",
            "FOREST",
            "DESERT",
            "ISLAND",
            "BEACH",
            "LAKE",
            "WATERFALL",
            "CANYON",
            "VOLCANO",
            "GLACIER",
            "MEADOW",
            "JUNGLE",
            "PRAIRIE",
            "CLIFF",
            "CAVE",
        ],
    },
    Theme {
        name: "Technology",
        words: &[
            "COMPUTER",
            "PHONE",
            "TABLET",
            "LAPTOP",
            "MOUSE",
            "KEYBOARD",
            "MONITOR",
            "PRINTER",
            "ROUTER",
            "MODEM",
            "WIFI",
            "BLUETOOTH",
            "SOFTWARE",
            "HARDWARE",
            "INTERNET",
            "EMAIL",
            "BROWSER",
            "DATABASE",
            "SERVER",
            "CLOUD",
        ],
    },
    Theme {
        name: "Occupations",
        words: &[
            "DOCTOR",
            "NURSE",
            "TEACHER",
            "LAWYER",
            "CHEF",
            "PILOT",
            "ARTIST",
            "WRITER",
            "FARMER",
            "BAKER",
            "ENGINEER",
            "SCIENTIST",
            "MUSICIAN",
            "ACTOR",
            "ATHLETE",
            "DESIGNER",
            "ARCHITECT",
            "MECHANIC",
            "PLUMBER",
            "DENTIST",
        ],
    },
];
