/**
 * Puzzle Service - Single Source of Truth for Puzzle Operations
 *
 * This service encapsulates all puzzle-related logic:
 * - Fetching puzzles from DB
 * - Generating puzzles on-demand (seed-based only)
 * - Handling race conditions
 * - Consistent error handling
 *
 * ARCHITECTURE:
 * - Seed-based games (14): Generated on-demand if not in DB
 * - LLM games (3): Must be pre-generated by workflow, throws if missing
 *
 * All date operations use UTC for global consistency.
 *
 * DATE HANDLING:
 * - This service uses Date objects (UTC midnight)
 * - Workflow uses string dates (YYYY-MM-DD) via registry.server.ts
 * - Both convert to seed (YYYYMMDD integer) for generation
 */

import {
	getGameConfig,
	getSeedFromDate,
	isValidGameSlug,
} from "@/games/registry";
import type { PuzzleDifficulty } from "@/games/types";
import { db } from "@/lib/db";
import { dailyPuzzles } from "@/lib/db/schema";
import { and, eq, isNull } from "drizzle-orm";

// ==========================================
// Types
// ==========================================

type PuzzleResult = {
	id: string;
	gameSlug: string;
	puzzleDate: Date;
	puzzleData: unknown;
	solution: unknown;
	difficulty: PuzzleDifficulty | null;
	seed: number | null;
	generatorVersion: string | null;
	createdAt: Date;
};

export type GetOrCreatePuzzleResult = {
	puzzle: PuzzleResult;
	wasGenerated: boolean;
};

// ==========================================
// Core Functions
// ==========================================

/**
 * Convert Date to date string (YYYY-MM-DD) in UTC
 */
function toDateString(date: Date): string {
	return date.toISOString().split("T")[0];
}

/**
 * Generate puzzle data for seed-based games only.
 *
 * Uses the same seed calculation as registry.server.ts for consistency.
 * Both use YYYYMMDD integer format.
 *
 * For games with difficulty support, the seed is offset by difficulty level
 * to ensure different puzzles per difficulty.
 *
 * @throws Error if game is LLM-based (must be pre-generated by workflow)
 */
function generatePuzzleData(
	gameSlug: string,
	date: Date,
	difficulty?: PuzzleDifficulty,
): { puzzleData: unknown; solution: unknown; seed: number } {
	const config = getGameConfig(gameSlug);
	if (!config) {
		throw new Error(`Unknown game: ${gameSlug}`);
	}

	// LLM games must have puzzles pre-generated - no silent fallback
	if (config.generationStrategy === "llm") {
		throw new Error(
			`[${gameSlug}] LLM-generated puzzle not found for ${toDateString(date)}. ` +
				`Puzzle generation workflow may have failed. Check workflow logs.`,
		);
	}

	// Use getSeedFromDate for consistency with registry.server.ts
	// Both produce YYYYMMDD integer (e.g., 20241228)
	// For difficulty-enabled games, add offset to ensure different puzzles per difficulty
	const baseSeed = getSeedFromDate(date);
	const difficultyOffset =
		difficulty === "easy"
			? 0
			: difficulty === "medium"
				? 1
				: difficulty === "hard"
					? 2
					: 0;
	const seed = baseSeed + difficultyOffset;

	const { puzzleData, solution } = config.generatePuzzle(seed, difficulty);

	return { puzzleData, solution, seed };
}

/**
 * Get or create a puzzle for a specific game and date.
 *
 * This is the SINGLE SOURCE OF TRUTH for puzzle retrieval/generation.
 * All endpoints should use this function instead of implementing their own logic.
 *
 * Features:
 * - Checks DB first
 * - Generates on-demand for seed-based games
 * - Handles race conditions with onConflictDoNothing + re-fetch
 * - Throws for LLM games if not pre-generated
 * - Supports difficulty levels for games with supportsDifficulty
 *
 * @param gameSlug - Game identifier
 * @param date - Puzzle date (must be UTC midnight)
 * @param difficulty - Optional difficulty level (for games with supportsDifficulty)
 * @returns Puzzle data and whether it was newly generated
 */
export async function getOrCreatePuzzle(
	gameSlug: string,
	date: Date,
	difficulty?: PuzzleDifficulty,
): Promise<GetOrCreatePuzzleResult> {
	if (!isValidGameSlug(gameSlug)) {
		throw new Error(`Invalid game slug: ${gameSlug}`);
	}

	// Build query conditions based on whether difficulty is provided
	// For games with difficulty: match specific difficulty level
	// For games without difficulty: match null difficulty
	const conditions = [
		eq(dailyPuzzles.gameSlug, gameSlug),
		eq(dailyPuzzles.puzzleDate, date),
	];

	if (difficulty) {
		conditions.push(eq(dailyPuzzles.difficulty, difficulty));
	} else {
		conditions.push(isNull(dailyPuzzles.difficulty));
	}

	// Try to fetch existing puzzle
	let puzzle = await db
		.select()
		.from(dailyPuzzles)
		.where(and(...conditions))
		.limit(1)
		.then((r) => r[0]);

	if (puzzle) {
		return { puzzle, wasGenerated: false };
	}

	// Puzzle doesn't exist - generate it
	// For LLM games, this will throw (they must be pre-generated)
	const { puzzleData, solution, seed } = generatePuzzleData(
		gameSlug,
		date,
		difficulty,
	);

	// Insert with race condition handling
	// If two users request the same puzzle simultaneously, one INSERT wins
	const [newPuzzle] = await db
		.insert(dailyPuzzles)
		.values({
			gameSlug,
			puzzleDate: date,
			puzzleData,
			solution,
			difficulty: difficulty ?? null,
			seed,
			generatorVersion: "v1.0",
		})
		.onConflictDoNothing()
		.returning();

	if (newPuzzle) {
		return { puzzle: newPuzzle, wasGenerated: true };
	}

	// Conflict occurred - another request won, fetch the winner's puzzle
	puzzle = await db
		.select()
		.from(dailyPuzzles)
		.where(and(...conditions))
		.limit(1)
		.then((r) => r[0]);

	if (!puzzle) {
		// This should never happen - indicates a serious bug
		throw new Error(
			`[${gameSlug}] Puzzle vanished after race condition handling. ` +
				`This is a critical bug - please report.`,
		);
	}

	return { puzzle, wasGenerated: false };
}

/**
 * Get puzzle by ID (for validation endpoints)
 */
async function _getPuzzleById(puzzleId: string): Promise<PuzzleResult | null> {
	const [puzzle] = await db
		.select()
		.from(dailyPuzzles)
		.where(eq(dailyPuzzles.id, puzzleId))
		.limit(1);

	return puzzle || null;
}

/**
 * Check if a puzzle exists for a game and date
 */
async function _puzzleExists(gameSlug: string, date: Date): Promise<boolean> {
	if (!isValidGameSlug(gameSlug)) return false;

	const [puzzle] = await db
		.select({ id: dailyPuzzles.id })
		.from(dailyPuzzles)
		.where(
			and(
				eq(dailyPuzzles.gameSlug, gameSlug),
				eq(dailyPuzzles.puzzleDate, date),
			),
		)
		.limit(1);

	return !!puzzle;
}
