/**
 * Frozen puzzles for unit tests.
 *
 * The daily puzzles are generated by the Rust pipeline; the per-game goldens
 * live in crates/puzzled-core/tests/fixtures/generate/<canonical-slug>.json.
 * Tests read one case from there instead of generating a puzzle in TypeScript.
 */

import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import type { GameConfig, PuzzleDifficulty } from './types'

const FIXTURE_DIR = join(import.meta.dir, '../../../../crates/puzzled-core/tests/fixtures/generate')
const CANONICAL: Record<string, string> = { queens: 'crowns', tango: 'duo' }

interface FrozenCase {
	difficulty: string | null
	puzzleData: unknown
	solution: unknown
}

export function frozenPuzzle<TPuzzleData, TSolution>(
	config: Pick<GameConfig<TPuzzleData, TSolution>, 'slug' | 'validateAndScore'>,
	difficulty?: PuzzleDifficulty,
): { puzzleData: TPuzzleData; solution: TSolution } {
	const slug = CANONICAL[config.slug] ?? config.slug
	const cases = JSON.parse(readFileSync(join(FIXTURE_DIR, `${slug}.json`), 'utf8')) as FrozenCase[]
	const found = cases.find(
		(c) => c.puzzleData !== undefined && (difficulty === undefined || c.difficulty === difficulty),
	)
	if (!found) throw new Error(`No frozen puzzle for ${slug} ${difficulty ?? ''}`)
	return found as unknown as { puzzleData: TPuzzleData; solution: TSolution }
}

/** One puzzle for crossword, which has no Rust golden; frozen from the retired TS generator. */
export function frozenCrossword<TPuzzleData, TSolution>(
	_config: Pick<GameConfig<TPuzzleData, TSolution>, 'slug' | 'validateAndScore'>,
): { puzzleData: TPuzzleData; solution: TSolution } {
	return JSON.parse(readFileSync(join(import.meta.dir, 'crossword/frozen-puzzle.json'), 'utf8'))
}
