/**
 * Session Replay Types
 *
 * Type definitions for the session replay system.
 * Built on rrweb with SOTA enhancements.
 */

import type { eventWithTime, recordOptions } from 'rrweb'

// ==========================================
// Configuration Types
// ==========================================

/**
 * Privacy modes for session replay
 *
 * - `strict`: Mask all text, inputs, and images
 * - `balanced`: Mask inputs and sensitive fields only
 * - `minimal`: Only mask explicitly marked fields
 */
export type PrivacyMode = 'strict' | 'balanced' | 'minimal'

/**
 * Sampling strategy for controlling recording volume
 */
export interface SamplingStrategy {
	/** Percentage of sessions to record (0-100) */
	rate: number
	/** Always record sessions with errors */
	alwaysRecordErrors: boolean
	/** Always record sessions matching these user segments */
	segments?: string[]
}

/**
 * Session replay configuration
 */
export interface SessionReplayConfig {
	/** Enable/disable session replay */
	enabled: boolean
	/** Sampling configuration */
	sampling: SamplingStrategy
	/** Maximum session duration in milliseconds (default: 60 min) */
	maxDuration: number
	/** Privacy mode */
	privacyMode: PrivacyMode
	/** Custom CSS selectors to always mask */
	maskSelectors: string[]
	/** Custom CSS selectors to always block (remove from recording) */
	blockSelectors: string[]
	/** Custom CSS selectors to ignore (don't record interactions) */
	ignoreSelectors: string[]

	// SOTA Features
	/** Correlate with error tracking */
	errorCorrelation: boolean
	/** Enable rage click detection */
	rageClickDetection: boolean
	/** Enable dead click detection */
	deadClickDetection: boolean
	/** Enable AI session summary */
	aiSummary: boolean
	/** Enable click heatmaps */
	heatmaps: boolean
	/** Enable network request capture */
	networkCapture: boolean
	/** Enable console log capture */
	consoleCapture: boolean

	// Performance
	/** Compress events before sending */
	compress: boolean
	/** Batch size for uploading events */
	batchSize: number
	/** Upload interval in milliseconds */
	uploadInterval: number
}

/**
 * Default configuration
 */
export const DEFAULT_CONFIG: SessionReplayConfig = {
	enabled: true,
	sampling: {
		rate: 100,
		alwaysRecordErrors: true,
	},
	maxDuration: 60 * 60 * 1000, // 60 minutes
	privacyMode: 'balanced',
	maskSelectors: [],
	blockSelectors: [],
	ignoreSelectors: [],
	errorCorrelation: true,
	rageClickDetection: true,
	deadClickDetection: true,
	aiSummary: false, // Opt-in for AI features
	heatmaps: true,
	networkCapture: true,
	consoleCapture: true,
	compress: true,
	batchSize: 50,
	uploadInterval: 5000,
}

// ==========================================
// Event Types
// ==========================================

/**
 * Custom event marker types
 */
export type MarkerType =
	| 'error'
	| 'rage-click'
	| 'dead-click'
	| 'navigation'
	| 'user-feedback'
	| 'conversion'
	| 'custom'

/**
 * Custom event marker for session timeline
 */
export interface SessionMarker {
	type: MarkerType
	timestamp: number
	payload: Record<string, unknown>
}

/**
 * Rage click detection result
 */
export interface RageClick {
	timestamp: number
	element: string
	selector: string
	clickCount: number
	duration: number
}

/**
 * Dead click detection result (click with no effect)
 */
export interface DeadClick {
	timestamp: number
	element: string
	selector: string
	expectedAction: string
}

/**
 * Network request capture
 */
export interface NetworkRequest {
	timestamp: number
	method: string
	url: string
	status: number
	duration: number
	requestSize?: number
	responseSize?: number
}

/**
 * Console log capture
 */
export interface ConsoleLog {
	timestamp: number
	level: 'log' | 'info' | 'warn' | 'error'
	message: string
	stack?: string
}

// ==========================================
// Session Types
// ==========================================

/**
 * Session metadata
 */
export interface SessionMetadata {
	sessionId: string
	userId?: string
	startTime: number
	endTime?: number
	url: string
	userAgent: string
	screenWidth: number
	screenHeight: number
	devicePixelRatio: number
	timezone: string
	language: string
}

/**
 * Session data for upload
 */
export interface SessionData {
	metadata: SessionMetadata
	events: eventWithTime[]
	markers: SessionMarker[]
	rageClicks: RageClick[]
	deadClicks: DeadClick[]
	networkRequests: NetworkRequest[]
	consoleLogs: ConsoleLog[]
}

/**
 * Session summary generated by AI
 */
export interface SessionSummary {
	sessionId: string
	summary: string
	keyEvents: string[]
	userIntent: string
	issues: string[]
	sentiment: 'positive' | 'neutral' | 'frustrated'
	generatedAt: number
}

// ==========================================
// Callback Types
// ==========================================

/**
 * Event callback for custom processing
 */
export type EventCallback = (event: eventWithTime) => void

/**
 * Upload callback for custom transport
 */
export type UploadCallback = (data: SessionData) => Promise<void>

/**
 * Error callback
 */
export type ErrorCallback = (error: Error) => void

// ==========================================
// Recorder State
// ==========================================

export type RecorderState = 'idle' | 'recording' | 'paused' | 'stopped'

/**
 * Recorder status
 */
export interface RecorderStatus {
	state: RecorderState
	sessionId: string | null
	eventCount: number
	startTime: number | null
	duration: number
	bytesRecorded: number
}
